// Code generated by cmd/generate. DO NOT EDIT.
package lib

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
)

type Client struct {
	BaseURL    string
	HTTPClient *http.Client
}

func NewClient(baseURL string) *Client {
	return &Client{BaseURL: baseURL, HTTPClient: http.DefaultClient}
}

func (c *Client) doRequest(method, path string, body interface{}) ([]byte, error) {
	var reqBody io.Reader
	if body != nil {
		b, err := json.Marshal(body)
		if err != nil {
			return nil, fmt.Errorf("marshal request body: %w", err)
		}
		reqBody = bytes.NewReader(b)
	}
	req, err := http.NewRequest(method, c.BaseURL+path, reqBody)
	if err != nil {
		return nil, err
	}
	if body != nil {
		req.Header.Set("Content-Type", "application/json")
	}
	resp, err := c.HTTPClient.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	data, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, err
	}
	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		return data, fmt.Errorf("HTTP %d: %s", resp.StatusCode, string(data))
	}
	return data, nil
}

func (c *Client) PostRestCancelSteamAuth() (json.RawMessage, error) {
	data, err := c.doRequest("POST", "/rest/cancelSteamAuth", nil)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) PostRestChat() (json.RawMessage, error) {
	data, err := c.doRequest("POST", "/rest/chat/", nil)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) RestChat() ([]interface{}, error) {
	data, err := c.doRequest("GET", "/rest/chat/", nil)
	if err != nil {
		return nil, err
	}
	var result []interface{}
	if err := json.Unmarshal(data, &result); err != nil {
		return nil, err
	}
	return result, nil
}

func (c *Client) PutRestGarage() (json.RawMessage, error) {
	data, err := c.doRequest("PUT", "/rest/garage/", nil)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) PostRestGarage(mod string, body interface{}) (json.RawMessage, error) {
	data, err := c.doRequest("POST", fmt.Sprintf("/rest/garage/%v", mod), body)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) PostRestGaragePOST(mod string, wheel string, body interface{}) (json.RawMessage, error) {
	data, err := c.doRequest("POST", fmt.Sprintf("/rest/garage/%v-%v", mod, wheel), body)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) PostRestGaragePitMenuLoadPitMenu() (json.RawMessage, error) {
	data, err := c.doRequest("POST", "/rest/garage/PitMenu/loadPitMenu", nil)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) RestGaragePitMenuReceivePitMenu() ([]RestGaragePitMenuReceivePitMenuResponseItem, error) {
	data, err := c.doRequest("GET", "/rest/garage/PitMenu/receivePitMenu", nil)
	if err != nil {
		return nil, err
	}
	var result []RestGaragePitMenuReceivePitMenuResponseItem
	if err := json.Unmarshal(data, &result); err != nil {
		return nil, err
	}
	return result, nil
}

func (c *Client) PostRestGarageSetCurrentVehicle() (json.RawMessage, error) {
	data, err := c.doRequest("POST", "/rest/garage/SetCurrentVehicle", nil)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) PostRestGarageSetPreviewSaveFile() (json.RawMessage, error) {
	data, err := c.doRequest("POST", "/rest/garage/SetPreviewSaveFile", nil)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) RestGarageUIScreenCarSetupOverview() (*RestGarageUIScreenCarSetupOverviewResponse, error) {
	data, err := c.doRequest("GET", "/rest/garage/UIScreen/CarSetupOverview", nil)
	if err != nil {
		return nil, err
	}
	var result RestGarageUIScreenCarSetupOverviewResponse
	if err := json.Unmarshal(data, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) RestGarageUIScreenCoopOverview() (json.RawMessage, error) {
	data, err := c.doRequest("GET", "/rest/garage/UIScreen/CoopOverview", nil)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) RestGarageUIScreenRepairAndRefuel() (*RestGarageUIScreenRepairAndRefuelResponse, error) {
	data, err := c.doRequest("GET", "/rest/garage/UIScreen/RepairAndRefuel", nil)
	if err != nil {
		return nil, err
	}
	var result RestGarageUIScreenRepairAndRefuelResponse
	if err := json.Unmarshal(data, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) RestGarageUIScreenSessionSetup() (*RestGarageUIScreenSessionSetupResponse, error) {
	data, err := c.doRequest("GET", "/rest/garage/UIScreen/SessionSetup", nil)
	if err != nil {
		return nil, err
	}
	var result RestGarageUIScreenSessionSetupResponse
	if err := json.Unmarshal(data, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) RestGarageUIScreenTireManagement() (*RestGarageUIScreenTireManagementResponse, error) {
	data, err := c.doRequest("GET", "/rest/garage/UIScreen/TireManagement", nil)
	if err != nil {
		return nil, err
	}
	var result RestGarageUIScreenTireManagementResponse
	if err := json.Unmarshal(data, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) RestGarageBrakeinfo() ([]float64, error) {
	data, err := c.doRequest("GET", "/rest/garage/brakeinfo", nil)
	if err != nil {
		return nil, err
	}
	var result []float64
	if err := json.Unmarshal(data, &result); err != nil {
		return nil, err
	}
	return result, nil
}

func (c *Client) PostRestGarageClearVehicleCache() (json.RawMessage, error) {
	data, err := c.doRequest("POST", "/rest/garage/clearVehicleCache", nil)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) PostRestGarageDrive() (json.RawMessage, error) {
	data, err := c.doRequest("POST", "/rest/garage/drive", nil)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) RestGarageGetPlayerGarageData() (*RestGarageGetPlayerGarageDataResponse, error) {
	data, err := c.doRequest("GET", "/rest/garage/getPlayerGarageData", nil)
	if err != nil {
		return nil, err
	}
	var result RestGarageGetPlayerGarageDataResponse
	if err := json.Unmarshal(data, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) RestGarageGetVehicleCondition() (*RestGarageGetVehicleConditionResponse, error) {
	data, err := c.doRequest("GET", "/rest/garage/getVehicleCondition", nil)
	if err != nil {
		return nil, err
	}
	var result RestGarageGetVehicleConditionResponse
	if err := json.Unmarshal(data, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) RestGarageInitVehicleCache() (json.RawMessage, error) {
	data, err := c.doRequest("GET", "/rest/garage/initVehicleCache", nil)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) RestGarageIsRefreshInProgress() (bool, error) {
	data, err := c.doRequest("GET", "/rest/garage/isRefreshInProgress", nil)
	if err != nil {
		return false, err
	}
	var result bool
	if err := json.Unmarshal(data, &result); err != nil {
		return false, err
	}
	return result, nil
}

func (c *Client) PostRestGarageRefreshSetups(body interface{}) (json.RawMessage, error) {
	data, err := c.doRequest("POST", "/rest/garage/refreshSetups", body)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) PutRestGarageSetup(body interface{}) (json.RawMessage, error) {
	data, err := c.doRequest("PUT", "/rest/garage/setup", body)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) RestGarageSetup() ([]RestGarageSetupResponseItem, error) {
	data, err := c.doRequest("GET", "/rest/garage/setup", nil)
	if err != nil {
		return nil, err
	}
	var result []RestGarageSetupResponseItem
	if err := json.Unmarshal(data, &result); err != nil {
		return nil, err
	}
	return result, nil
}

func (c *Client) PostRestGarageSetup(body interface{}) (json.RawMessage, error) {
	data, err := c.doRequest("POST", "/rest/garage/setup", body)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) DeleteRestGarageSetup(setup string) (json.RawMessage, error) {
	data, err := c.doRequest("DELETE", fmt.Sprintf("/rest/garage/setup/%v", setup), nil)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) PostRestGarageSetupCompare(body interface{}) (json.RawMessage, error) {
	data, err := c.doRequest("POST", "/rest/garage/setup/compare", body)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) PostRestGarageSetupDefault() (json.RawMessage, error) {
	data, err := c.doRequest("POST", "/rest/garage/setup/default", nil)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) PostRestGarageSetupNotes(body interface{}) (json.RawMessage, error) {
	data, err := c.doRequest("POST", "/rest/garage/setup/notes", body)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) RestGarageSetupNotes(setup string) (json.RawMessage, error) {
	data, err := c.doRequest("GET", fmt.Sprintf("/rest/garage/setup/notes/%v", setup), nil)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) RestGarageShowOnlyRelevantSetups() (bool, error) {
	data, err := c.doRequest("GET", "/rest/garage/showOnlyRelevantSetups", nil)
	if err != nil {
		return false, err
	}
	var result bool
	if err := json.Unmarshal(data, &result); err != nil {
		return false, err
	}
	return result, nil
}

func (c *Client) PostRestGarageShowOnlyRelevantSetups(body interface{}) (json.RawMessage, error) {
	data, err := c.doRequest("POST", "/rest/garage/showOnlyRelevantSetups", body)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) RestGarageSummary() (*RestGarageSummaryResponse, error) {
	data, err := c.doRequest("GET", "/rest/garage/summary", nil)
	if err != nil {
		return nil, err
	}
	var result RestGarageSummaryResponse
	if err := json.Unmarshal(data, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) RestGarageTireinfo() (*RestGarageTireinfoResponse, error) {
	data, err := c.doRequest("GET", "/rest/garage/tireinfo", nil)
	if err != nil {
		return nil, err
	}
	var result RestGarageTireinfoResponse
	if err := json.Unmarshal(data, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) PostRestGarageToRaceMenu() (json.RawMessage, error) {
	data, err := c.doRequest("POST", "/rest/garage/toRaceMenu", nil)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) RestHud() (*RestHudResponse, error) {
	data, err := c.doRequest("GET", "/rest/hud", nil)
	if err != nil {
		return nil, err
	}
	var result RestHudResponse
	if err := json.Unmarshal(data, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) PostRestHudToggleComponent(component string) (json.RawMessage, error) {
	data, err := c.doRequest("POST", fmt.Sprintf("/rest/hud/toggle/%v", component), nil)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) PostRestLiveryeditorSetCameraCamera(camera string) (json.RawMessage, error) {
	data, err := c.doRequest("POST", fmt.Sprintf("/rest/liveryeditor/setCamera/%v", camera), nil)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) PostRestLiveryeditorShowRegionTextureActive(active bool) (json.RawMessage, error) {
	data, err := c.doRequest("POST", fmt.Sprintf("/rest/liveryeditor/showRegionTexture/%v", active), nil)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) PostRestLiveryeditorSubmitCustomSkin() (json.RawMessage, error) {
	data, err := c.doRequest("POST", "/rest/liveryeditor/submitCustomSkin", nil)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) RestMaterialeditorDownloadMaterialGuid(materialGuid string) (json.RawMessage, error) {
	data, err := c.doRequest("GET", fmt.Sprintf("/rest/materialeditor/download/%v", materialGuid), nil)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) RestMaterialeditorLiveryeditorGetCustomSkinInfo() (*RestMaterialeditorLiveryeditorGetCustomSkinInfoResponse, error) {
	data, err := c.doRequest("GET", "/rest/materialeditor/liveryeditor/getCustomSkinInfo", nil)
	if err != nil {
		return nil, err
	}
	var result RestMaterialeditorLiveryeditorGetCustomSkinInfoResponse
	if err := json.Unmarshal(data, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) PostRestMaterialeditorLiveryeditorReloadCustomSkin() (json.RawMessage, error) {
	data, err := c.doRequest("POST", "/rest/materialeditor/liveryeditor/reloadCustomSkin", nil)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) RestMaterialeditorMaterialGuid(materialGuid string) (json.RawMessage, error) {
	data, err := c.doRequest("GET", fmt.Sprintf("/rest/materialeditor/%v", materialGuid), nil)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) PutRestMaterialeditorMaterialGuid(materialGuid string, body interface{}) (json.RawMessage, error) {
	data, err := c.doRequest("PUT", fmt.Sprintf("/rest/materialeditor/%v", materialGuid), body)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) PostRestMaterialeditorMaterialGuidPersist(materialGuid string, body interface{}) (json.RawMessage, error) {
	data, err := c.doRequest("POST", fmt.Sprintf("/rest/materialeditor/%v/persist", materialGuid), body)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) PutRestMaterialeditorMaterialGuidShader(materialGuid string, body interface{}) (json.RawMessage, error) {
	data, err := c.doRequest("PUT", fmt.Sprintf("/rest/materialeditor/%v/shader", materialGuid), body)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) RestMaterialeditorMaterialGuidMap(materialGuid string, mapParam string, thumbSize int, r string) (json.RawMessage, error) {
	data, err := c.doRequest("GET", fmt.Sprintf("/rest/materialeditor/%v/%v", materialGuid, mapParam, thumbSize), nil)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) PostRestMultiplayerCancelJoinRequest() (json.RawMessage, error) {
	data, err := c.doRequest("POST", "/rest/multiplayer/cancelJoinRequest", nil)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) PostRestMultiplayerExitVehicle() (json.RawMessage, error) {
	data, err := c.doRequest("POST", "/rest/multiplayer/exitVehicle", nil)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) RestMultiplayerJoin(password string, authentication string, teamName string, vehicleNumber string, paintBlobId string, host string, port int) (json.RawMessage, error) {
	data, err := c.doRequest("GET", fmt.Sprintf("/rest/multiplayer/join", password, authentication, teamName, vehicleNumber, paintBlobId), nil)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) RestMultiplayerJoinState() (string, error) {
	data, err := c.doRequest("GET", "/rest/multiplayer/join/state", nil)
	if err != nil {
		return "", err
	}
	var result string
	if err := json.Unmarshal(data, &result); err != nil {
		return "", err
	}
	return result, nil
}

func (c *Client) RestMultiplayerSteamStatus() (bool, error) {
	data, err := c.doRequest("GET", "/rest/multiplayer/steam/status", nil)
	if err != nil {
		return false, err
	}
	var result bool
	if err := json.Unmarshal(data, &result); err != nil {
		return false, err
	}
	return result, nil
}

func (c *Client) PostRestMultiplayerTakeControlOfVehicle() (json.RawMessage, error) {
	data, err := c.doRequest("POST", "/rest/multiplayer/takeControlOfVehicle", nil)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) RestMultiplayerTeams() (interface{}, error) {
	data, err := c.doRequest("GET", "/rest/multiplayer/teams", nil)
	if err != nil {
		return nil, err
	}
	var result interface{}
	if err := json.Unmarshal(data, &result); err != nil {
		return nil, err
	}
	return result, nil
}

func (c *Client) NavigationGetLoadingScreen() (*NavigationGetLoadingScreenResponse, error) {
	data, err := c.doRequest("GET", "/navigation/GetLoadingScreen", nil)
	if err != nil {
		return nil, err
	}
	var result NavigationGetLoadingScreenResponse
	if err := json.Unmarshal(data, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) PostNavigationActionAction(action string) (json.RawMessage, error) {
	data, err := c.doRequest("POST", fmt.Sprintf("/navigation/action/%v", action), nil)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) NavigationGetReferrer() (*NavigationGetReferrerResponse, error) {
	data, err := c.doRequest("GET", "/navigation/getReferrer", nil)
	if err != nil {
		return nil, err
	}
	var result NavigationGetReferrerResponse
	if err := json.Unmarshal(data, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) PostNavigationOpenLiveryEditor() (json.RawMessage, error) {
	data, err := c.doRequest("POST", "/navigation/openLiveryEditor", nil)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) PostNavigationSendToLog() (json.RawMessage, error) {
	data, err := c.doRequest("POST", "/navigation/sendToLog", nil)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) PostNavigationSetReferrer() (json.RawMessage, error) {
	data, err := c.doRequest("POST", "/navigation/setReferrer", nil)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) NavigationState() (*NavigationStateResponse, error) {
	data, err := c.doRequest("GET", "/navigation/state", nil)
	if err != nil {
		return nil, err
	}
	var result NavigationStateResponse
	if err := json.Unmarshal(data, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) PostRestOptionsApplyVideoOptions() (json.RawMessage, error) {
	data, err := c.doRequest("POST", "/rest/options/ApplyVideoOptions", nil)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) RestOptionsUIScreenControls() (*RestOptionsUIScreenControlsResponse, error) {
	data, err := c.doRequest("GET", "/rest/options/UIScreen/Controls", nil)
	if err != nil {
		return nil, err
	}
	var result RestOptionsUIScreenControlsResponse
	if err := json.Unmarshal(data, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) PostRestOptionsAssignCancel() (json.RawMessage, error) {
	data, err := c.doRequest("POST", "/rest/options/assign/cancel", nil)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) RestOptionsAssignChangestatus() (*RestOptionsAssignChangestatusResponse, error) {
	data, err := c.doRequest("GET", "/rest/options/assign/changestatus", nil)
	if err != nil {
		return nil, err
	}
	var result RestOptionsAssignChangestatusResponse
	if err := json.Unmarshal(data, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) PostRestOptionsAssignConfirm() (json.RawMessage, error) {
	data, err := c.doRequest("POST", "/rest/options/assign/confirm", nil)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) RestOptionsCommandline() (*RestOptionsCommandlineResponse, error) {
	data, err := c.doRequest("GET", "/rest/options/commandline", nil)
	if err != nil {
		return nil, err
	}
	var result RestOptionsCommandlineResponse
	if err := json.Unmarshal(data, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) RestOptionsDisplay() (*RestOptionsDisplayResponse, error) {
	data, err := c.doRequest("GET", "/rest/options/display", nil)
	if err != nil {
		return nil, err
	}
	var result RestOptionsDisplayResponse
	if err := json.Unmarshal(data, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) PostRestOptionsFloat(body interface{}) (json.RawMessage, error) {
	data, err := c.doRequest("POST", "/rest/options/float", body)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) RestOptionsGetAllResolutions() ([]RestOptionsGetAllResolutionsResponseItem, error) {
	data, err := c.doRequest("GET", "/rest/options/getAllResolutions", nil)
	if err != nil {
		return nil, err
	}
	var result []RestOptionsGetAllResolutionsResponseItem
	if err := json.Unmarshal(data, &result); err != nil {
		return nil, err
	}
	return result, nil
}

func (c *Client) RestOptionsGetLanguage() (*RestOptionsGetLanguageResponse, error) {
	data, err := c.doRequest("GET", "/rest/options/getLanguage", nil)
	if err != nil {
		return nil, err
	}
	var result RestOptionsGetLanguageResponse
	if err := json.Unmarshal(data, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) PostRestOptionsGraphicsConfirmgraphics() (json.RawMessage, error) {
	data, err := c.doRequest("POST", "/rest/options/graphics/confirmgraphics", nil)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) PostRestOptionsGraphicsResetgraphics() (json.RawMessage, error) {
	data, err := c.doRequest("POST", "/rest/options/graphics/resetgraphics", nil)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) RestOptionsLiveInputs() (*RestOptionsLiveInputsResponse, error) {
	data, err := c.doRequest("GET", "/rest/options/liveInputs", nil)
	if err != nil {
		return nil, err
	}
	var result RestOptionsLiveInputsResponse
	if err := json.Unmarshal(data, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) PostRestOptionsLong(body interface{}) (json.RawMessage, error) {
	data, err := c.doRequest("POST", "/rest/options/long", body)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) RestOptionsResetVRView() (json.RawMessage, error) {
	data, err := c.doRequest("GET", "/rest/options/resetVRView", nil)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) PostRestOptionsSetConfigControl(body interface{}) (json.RawMessage, error) {
	data, err := c.doRequest("POST", "/rest/options/setConfigControl", body)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) PostRestOptionsSetControls() (json.RawMessage, error) {
	data, err := c.doRequest("POST", "/rest/options/setControls", nil)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) PutRestOptionsSetInMenuGfxEffects() (json.RawMessage, error) {
	data, err := c.doRequest("PUT", "/rest/options/setInMenuGfxEffects", nil)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) PostRestOptionsSetInputAxisProperties() (json.RawMessage, error) {
	data, err := c.doRequest("POST", "/rest/options/setInputAxisProperties", nil)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) RestOptionsSettings() (*RestOptionsSettingsResponse, error) {
	data, err := c.doRequest("GET", "/rest/options/settings", nil)
	if err != nil {
		return nil, err
	}
	var result RestOptionsSettingsResponse
	if err := json.Unmarshal(data, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) PostRestOptionsUnsetConfigControl(body interface{}) (json.RawMessage, error) {
	data, err := c.doRequest("POST", "/rest/options/unsetConfigControl", body)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) RestProfile() (*RestProfileResponse, error) {
	data, err := c.doRequest("GET", "/rest/profile/", nil)
	if err != nil {
		return nil, err
	}
	var result RestProfileResponse
	if err := json.Unmarshal(data, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) PostRestProfileDLCViewDLC() (json.RawMessage, error) {
	data, err := c.doRequest("POST", "/rest/profile/DLC/viewDLC", nil)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) RestProfileEacActive() (bool, error) {
	data, err := c.doRequest("GET", "/rest/profile/eacActive", nil)
	if err != nil {
		return false, err
	}
	var result bool
	if err := json.Unmarshal(data, &result); err != nil {
		return false, err
	}
	return result, nil
}

func (c *Client) RestProfileFirstRun() (bool, error) {
	data, err := c.doRequest("GET", "/rest/profile/firstRun", nil)
	if err != nil {
		return false, err
	}
	var result bool
	if err := json.Unmarshal(data, &result); err != nil {
		return false, err
	}
	return result, nil
}

func (c *Client) RestProfileGetAuthSessionTicket() (*RestProfileGetAuthSessionTicketResponse, error) {
	data, err := c.doRequest("GET", "/rest/profile/getAuthSessionTicket", nil)
	if err != nil {
		return nil, err
	}
	var result RestProfileGetAuthSessionTicketResponse
	if err := json.Unmarshal(data, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) RestProfileInDevMode() (bool, error) {
	data, err := c.doRequest("GET", "/rest/profile/inDevMode", nil)
	if err != nil {
		return false, err
	}
	var result bool
	if err := json.Unmarshal(data, &result); err != nil {
		return false, err
	}
	return result, nil
}

func (c *Client) RestProfileProfileInfoGetProfileInfo() (*RestProfileProfileInfoGetProfileInfoResponse, error) {
	data, err := c.doRequest("GET", "/rest/profile/profileInfo/getProfileInfo", nil)
	if err != nil {
		return nil, err
	}
	var result RestProfileProfileInfoGetProfileInfoResponse
	if err := json.Unmarshal(data, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) PostRestProfileProfileInfoSetProfileInfo(body interface{}) (json.RawMessage, error) {
	data, err := c.doRequest("POST", "/rest/profile/profileInfo/setProfileInfo", body)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) RestRaceCar() ([]RestRaceCarResponseItem, error) {
	data, err := c.doRequest("GET", "/rest/race/car", nil)
	if err != nil {
		return nil, err
	}
	var result []RestRaceCarResponseItem
	if err := json.Unmarshal(data, &result); err != nil {
		return nil, err
	}
	return result, nil
}

func (c *Client) RestRaceCarIdImage(id string, typeParam string) (json.RawMessage, error) {
	data, err := c.doRequest("GET", fmt.Sprintf("/rest/race/car/%v/image", id), nil)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) RestRaceGetAllowedToStartRacing() (bool, error) {
	data, err := c.doRequest("GET", "/rest/race/getAllowedToStartRacing", nil)
	if err != nil {
		return false, err
	}
	var result bool
	if err := json.Unmarshal(data, &result); err != nil {
		return false, err
	}
	return result, nil
}

func (c *Client) PostRestRaceStartRace() (json.RawMessage, error) {
	data, err := c.doRequest("POST", "/rest/race/startRace", nil)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) PostRestRaceTrack(body interface{}) (json.RawMessage, error) {
	data, err := c.doRequest("POST", "/rest/race/track", body)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) RestRaceTrack() ([]RestRaceTrackResponseItem, error) {
	data, err := c.doRequest("GET", "/rest/race/track", nil)
	if err != nil {
		return nil, err
	}
	var result []RestRaceTrackResponseItem
	if err := json.Unmarshal(data, &result); err != nil {
		return nil, err
	}
	return result, nil
}

func (c *Client) RestRaceTrackIdTrackmap(id string) (json.RawMessage, error) {
	data, err := c.doRequest("GET", fmt.Sprintf("/rest/race/track/%v/trackmap", id), nil)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) RestReplayCameraControllerGetCameraInfo() (*RestReplayCameraControllerGetCameraInfoResponse, error) {
	data, err := c.doRequest("GET", "/rest/replay/CameraController/getCameraInfo", nil)
	if err != nil {
		return nil, err
	}
	var result RestReplayCameraControllerGetCameraInfoResponse
	if err := json.Unmarshal(data, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) PostRestReplayCameraControllerSetCamera() (json.RawMessage, error) {
	data, err := c.doRequest("POST", "/rest/replay/CameraController/setCamera", nil)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) RestReplayIsActive() (bool, error) {
	data, err := c.doRequest("GET", "/rest/replay/isActive", nil)
	if err != nil {
		return false, err
	}
	var result bool
	if err := json.Unmarshal(data, &result); err != nil {
		return false, err
	}
	return result, nil
}

func (c *Client) PostRestReplayToggleactive() (json.RawMessage, error) {
	data, err := c.doRequest("POST", "/rest/replay/toggleactive", nil)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) RestSessions() (*RestSessionsResponse, error) {
	data, err := c.doRequest("GET", "/rest/sessions/?", nil)
	if err != nil {
		return nil, err
	}
	var result RestSessionsResponse
	if err := json.Unmarshal(data, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) PostRestSessionsChampionshipGetCurrentChampTemplate() (json.RawMessage, error) {
	data, err := c.doRequest("POST", "/rest/sessions/Championship/getCurrentChampTemplate", nil)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) PostRestSessionsChampionshipGetGrid() (json.RawMessage, error) {
	data, err := c.doRequest("POST", "/rest/sessions/Championship/getGrid", nil)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) PostRestSessionsChampionshipSetCurrentChampionshipTemplate() (json.RawMessage, error) {
	data, err := c.doRequest("POST", "/rest/sessions/Championship/setCurrentChampionshipTemplate", nil)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) PostRestSessionsCoopSetCoopDriverID() (json.RawMessage, error) {
	data, err := c.doRequest("POST", "/rest/sessions/Coop/setCoopDriverID", nil)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) PostRestSessionsFFtoRaceEnd() (json.RawMessage, error) {
	data, err := c.doRequest("POST", "/rest/sessions/FFtoRaceEnd", nil)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) RestSessionsGetGameState() (*RestSessionsGetGameStateResponse, error) {
	data, err := c.doRequest("GET", "/rest/sessions/GetGameState", nil)
	if err != nil {
		return nil, err
	}
	var result RestSessionsGetGameStateResponse
	if err := json.Unmarshal(data, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) RestSessionsGetSessionsInfoForEvent() (*RestSessionsGetSessionsInfoForEventResponse, error) {
	data, err := c.doRequest("GET", "/rest/sessions/GetSessionsInfoForEvent", nil)
	if err != nil {
		return nil, err
	}
	var result RestSessionsGetSessionsInfoForEventResponse
	if err := json.Unmarshal(data, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) PostRestSessionsMultiStintRaceDrive() (json.RawMessage, error) {
	data, err := c.doRequest("POST", "/rest/sessions/MultiStintRace/Drive", nil)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) PostRestSessionsMultiStintRaceUnPause() (json.RawMessage, error) {
	data, err := c.doRequest("POST", "/rest/sessions/MultiStintRace/UnPause", nil)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) PostRestSessionsMultiStintRaceSetDriverInfo() (json.RawMessage, error) {
	data, err := c.doRequest("POST", "/rest/sessions/MultiStintRace/setDriverInfo", nil)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) PostRestSessionsSaveLoadCompressSaveFile() (json.RawMessage, error) {
	data, err := c.doRequest("POST", "/rest/sessions/SaveLoad/compressSaveFile", nil)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) PostRestSessionsSaveLoadDecompressSaveFile() (json.RawMessage, error) {
	data, err := c.doRequest("POST", "/rest/sessions/SaveLoad/decompressSaveFile", nil)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) PostRestSessionsSaveLoadDeleteSaveFile() (json.RawMessage, error) {
	data, err := c.doRequest("POST", "/rest/sessions/SaveLoad/deleteSaveFile", nil)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) PostRestSessionsSaveLoadDoesBackupExistForThisSession() (json.RawMessage, error) {
	data, err := c.doRequest("POST", "/rest/sessions/SaveLoad/doesBackupExistForThisSession", nil)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) PostRestSessionsSaveLoadGenerateSaveFileFromSessionPreset(body interface{}) (json.RawMessage, error) {
	data, err := c.doRequest("POST", "/rest/sessions/SaveLoad/generateSaveFileFromSessionPreset", body)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) PostRestSessionsSaveLoadGetEveryLocalSave() (json.RawMessage, error) {
	data, err := c.doRequest("POST", "/rest/sessions/SaveLoad/getEveryLocalSave", nil)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) PostRestSessionsSaveLoadGetNumSaves() (json.RawMessage, error) {
	data, err := c.doRequest("POST", "/rest/sessions/SaveLoad/getNumSaves", nil)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) RestSessionsSaveLoadGetSaveJSON() (*RestSessionsSaveLoadGetSaveJSONResponse, error) {
	data, err := c.doRequest("GET", "/rest/sessions/SaveLoad/getSaveJSON", nil)
	if err != nil {
		return nil, err
	}
	var result RestSessionsSaveLoadGetSaveJSONResponse
	if err := json.Unmarshal(data, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) PostRestSessionsSaveLoadIsSaveNameValid(body interface{}) (json.RawMessage, error) {
	data, err := c.doRequest("POST", "/rest/sessions/SaveLoad/isSaveNameValid", body)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) PostRestSessionsSaveLoadLoadGame() (json.RawMessage, error) {
	data, err := c.doRequest("POST", "/rest/sessions/SaveLoad/loadGame", nil)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) PostRestSessionsSaveLoadSaveGame() (json.RawMessage, error) {
	data, err := c.doRequest("POST", "/rest/sessions/SaveLoad/saveGame", nil)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) PostRestSessionsSaveLoadSaveLastBackup() (json.RawMessage, error) {
	data, err := c.doRequest("POST", "/rest/sessions/SaveLoad/saveLastBackup", nil)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) PostRestSessionsSaveLoadSaveTemplateToFile() (json.RawMessage, error) {
	data, err := c.doRequest("POST", "/rest/sessions/SaveLoad/saveTemplateToFile", nil)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) PostRestSessionsSessionPresetsApplyPreset() (json.RawMessage, error) {
	data, err := c.doRequest("POST", "/rest/sessions/SessionPresets/applyPreset", nil)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) PostRestSessionsSessionPresetsGetDefaultPresetForTrack() (json.RawMessage, error) {
	data, err := c.doRequest("POST", "/rest/sessions/SessionPresets/getDefaultPresetForTrack", nil)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) PostRestSessionsSessionPresetsRequestPreset() (json.RawMessage, error) {
	data, err := c.doRequest("POST", "/rest/sessions/SessionPresets/requestPreset", nil)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) PostRestSessionsAiTakeDriverControl() (json.RawMessage, error) {
	data, err := c.doRequest("POST", "/rest/sessions/ai/TakeDriverControl", nil)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) PostRestSessionsAiForcePlayerVehAiPit() (json.RawMessage, error) {
	data, err := c.doRequest("POST", "/rest/sessions/ai/forcePlayerVehAiPit", nil)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) RestSessionsAmount() (*RestSessionsAmountResponse, error) {
	data, err := c.doRequest("GET", "/rest/sessions/amount", nil)
	if err != nil {
		return nil, err
	}
	var result RestSessionsAmountResponse
	if err := json.Unmarshal(data, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) PostRestSessionsClearEventNotification(body interface{}) (json.RawMessage, error) {
	data, err := c.doRequest("POST", "/rest/sessions/clearEventNotification", body)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) PostRestSessionsContinueGame() (json.RawMessage, error) {
	data, err := c.doRequest("POST", "/rest/sessions/continueGame", nil)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) PostRestSessionsGetAllAvailableVehicles(body interface{}) (json.RawMessage, error) {
	data, err := c.doRequest("POST", "/rest/sessions/getAllAvailableVehicles", body)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) RestSessionsGetAllVehicles() ([]RestSessionsGetAllVehiclesResponseItem, error) {
	data, err := c.doRequest("GET", "/rest/sessions/getAllVehicles", nil)
	if err != nil {
		return nil, err
	}
	var result []RestSessionsGetAllVehiclesResponseItem
	if err := json.Unmarshal(data, &result); err != nil {
		return nil, err
	}
	return result, nil
}

func (c *Client) RestSessionsGetTracksInSeries() ([]RestSessionsGetTracksInSeriesResponseItem, error) {
	data, err := c.doRequest("GET", "/rest/sessions/getTracksInSeries", nil)
	if err != nil {
		return nil, err
	}
	var result []RestSessionsGetTracksInSeriesResponseItem
	if err := json.Unmarshal(data, &result); err != nil {
		return nil, err
	}
	return result, nil
}

func (c *Client) PostRestSessionsNotifyInPauseSettings(body interface{}) (json.RawMessage, error) {
	data, err := c.doRequest("POST", "/rest/sessions/notifyInPauseSettings", body)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) RestSessionsOpponents() ([]RestSessionsOpponentsResponseItem, error) {
	data, err := c.doRequest("GET", "/rest/sessions/opponents", nil)
	if err != nil {
		return nil, err
	}
	var result []RestSessionsOpponentsResponseItem
	if err := json.Unmarshal(data, &result); err != nil {
		return nil, err
	}
	return result, nil
}

func (c *Client) RestSessionsOpponentsAll() ([]RestSessionsOpponentsAllResponseItem, error) {
	data, err := c.doRequest("GET", "/rest/sessions/opponents/all", nil)
	if err != nil {
		return nil, err
	}
	var result []RestSessionsOpponentsAllResponseItem
	if err := json.Unmarshal(data, &result); err != nil {
		return nil, err
	}
	return result, nil
}

func (c *Client) PostRestSessionsPlayVOTrigger() (json.RawMessage, error) {
	data, err := c.doRequest("POST", "/rest/sessions/playVOTrigger", nil)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) PostRestSessionsPlayerSettingsBackupPlayerSettings() (json.RawMessage, error) {
	data, err := c.doRequest("POST", "/rest/sessions/playerSettings/backupPlayerSettings", nil)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) PostRestSessionsPlayerSettingsRestorePlayerSettingsFromBackup() (json.RawMessage, error) {
	data, err := c.doRequest("POST", "/rest/sessions/playerSettings/restorePlayerSettingsFromBackup", nil)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) PostRestSessionsRaceControlVerification() (json.RawMessage, error) {
	data, err := c.doRequest("POST", "/rest/sessions/raceControlVerification", nil)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) PostRestSessionsRestartStintAvailable() (json.RawMessage, error) {
	data, err := c.doRequest("POST", "/rest/sessions/restartStintAvailable", nil)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) RestSessionsRestartStintAvailable() (*RestSessionsRestartStintAvailableResponse, error) {
	data, err := c.doRequest("GET", "/rest/sessions/restartStintAvailable", nil)
	if err != nil {
		return nil, err
	}
	var result RestSessionsRestartStintAvailableResponse
	if err := json.Unmarshal(data, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) PostRestSessionsResumePitStop() (json.RawMessage, error) {
	data, err := c.doRequest("POST", "/rest/sessions/resumePitStop", nil)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) PostRestSessionsReturnToMonitor() (json.RawMessage, error) {
	data, err := c.doRequest("POST", "/rest/sessions/returnToMonitor", nil)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) PostRestSessionsSaveloadGetSaveFileJSONFromFilename(body interface{}) (json.RawMessage, error) {
	data, err := c.doRequest("POST", "/rest/sessions/saveload/getSaveFileJSONFromFilename", body)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) PostRestSessionsSetEventNotification(body interface{}) (json.RawMessage, error) {
	data, err := c.doRequest("POST", "/rest/sessions/setEventNotification", body)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) PostRestSessionsSetHudOnWatchScreen(body interface{}) (json.RawMessage, error) {
	data, err := c.doRequest("POST", "/rest/sessions/setHudOnWatchScreen", body)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) PostRestSessionsSettings(body interface{}) (json.RawMessage, error) {
	data, err := c.doRequest("POST", "/rest/sessions/settings", body)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) RestSessionsWeather() (*RestSessionsWeatherResponse, error) {
	data, err := c.doRequest("GET", "/rest/sessions/weather", nil)
	if err != nil {
		return nil, err
	}
	var result RestSessionsWeatherResponse
	if err := json.Unmarshal(data, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) PostRestSessionsWeatherSessionNodeSetting(session string, node string, setting string, body interface{}) (json.RawMessage, error) {
	data, err := c.doRequest("POST", fmt.Sprintf("/rest/sessions/weather/%v/%v/%v", session, node, setting), body)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) PostRestSessionsWeatherSessionPreset(session string, preset string) (json.RawMessage, error) {
	data, err := c.doRequest("POST", fmt.Sprintf("/rest/sessions/weather/%v/%v", session, preset), nil)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) PostRestSessionsSessionSessions(session string) (json.RawMessage, error) {
	data, err := c.doRequest("POST", fmt.Sprintf("/rest/sessions/%v/sessions", session), nil)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) PostRestStartOpenExternalBrowserToURL() (json.RawMessage, error) {
	data, err := c.doRequest("POST", "/rest/start/openExternalBrowserToURL", nil)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) RestStrategyOverall() (json.RawMessage, error) {
	data, err := c.doRequest("GET", "/rest/strategy/overall", nil)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) RestStrategyPitstopEstimate() (*RestStrategyPitstopEstimateResponse, error) {
	data, err := c.doRequest("GET", "/rest/strategy/pitstop-estimate", nil)
	if err != nil {
		return nil, err
	}
	var result RestStrategyPitstopEstimateResponse
	if err := json.Unmarshal(data, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) RestStrategyUsage() (*RestStrategyUsageResponse, error) {
	data, err := c.doRequest("GET", "/rest/strategy/usage", nil)
	if err != nil {
		return nil, err
	}
	var result RestStrategyUsageResponse
	if err := json.Unmarshal(data, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) RestWatchFocus() (int64, error) {
	data, err := c.doRequest("GET", "/rest/watch/focus", nil)
	if err != nil {
		return 0, err
	}
	var result int64
	if err := json.Unmarshal(data, &result); err != nil {
		return 0, err
	}
	return result, nil
}

func (c *Client) PutRestWatchFocusCameraTypeTrackSideGroupShouldAdvance(cameraType int, trackSideGroup int, shouldAdvance bool) (json.RawMessage, error) {
	data, err := c.doRequest("PUT", fmt.Sprintf("/rest/watch/focus/%v/%v/%v", cameraType, trackSideGroup, shouldAdvance), nil)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) PutRestWatchFocusSlotid(slotid int) (json.RawMessage, error) {
	data, err := c.doRequest("PUT", fmt.Sprintf("/rest/watch/focus/%v", slotid), nil)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) PutRestWatchFocusBackward() (json.RawMessage, error) {
	data, err := c.doRequest("PUT", "/rest/watch/focusBackward", nil)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) PutRestWatchFocusForward() (json.RawMessage, error) {
	data, err := c.doRequest("PUT", "/rest/watch/focusForward", nil)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) RestWatchPlayId(id int) (json.RawMessage, error) {
	data, err := c.doRequest("GET", fmt.Sprintf("/rest/watch/play/%v", id), nil)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) RestWatchReplayGetReplayFolder() (*RestWatchReplayGetReplayFolderResponse, error) {
	data, err := c.doRequest("GET", "/rest/watch/replay/getReplayFolder", nil)
	if err != nil {
		return nil, err
	}
	var result RestWatchReplayGetReplayFolderResponse
	if err := json.Unmarshal(data, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) PutRestWatchReplaySetCurrentMetadata() (json.RawMessage, error) {
	data, err := c.doRequest("PUT", "/rest/watch/replay/setCurrentMetadata", nil)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) PostRestWatchReplaySetReplayUIVisible() (json.RawMessage, error) {
	data, err := c.doRequest("POST", "/rest/watch/replay/setReplayUIVisible", nil)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) PutRestWatchReplayCommandCommand(command string) (json.RawMessage, error) {
	data, err := c.doRequest("PUT", fmt.Sprintf("/rest/watch/replayCommand/%v", command), nil)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) RestWatchReplays() ([]RestWatchReplaysResponseItem, error) {
	data, err := c.doRequest("GET", "/rest/watch/replays", nil)
	if err != nil {
		return nil, err
	}
	var result []RestWatchReplaysResponseItem
	if err := json.Unmarshal(data, &result); err != nil {
		return nil, err
	}
	return result, nil
}

func (c *Client) PutRestWatchReplaytimeTime(time float64) (json.RawMessage, error) {
	data, err := c.doRequest("PUT", fmt.Sprintf("/rest/watch/replaytime/%v", time), nil)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) RestWatchSessionInfo() (*RestWatchSessionInfoResponse, error) {
	data, err := c.doRequest("GET", "/rest/watch/sessionInfo", nil)
	if err != nil {
		return nil, err
	}
	var result RestWatchSessionInfoResponse
	if err := json.Unmarshal(data, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) RestWatchStandings() ([]RestWatchStandingsResponseItem, error) {
	data, err := c.doRequest("GET", "/rest/watch/standings", nil)
	if err != nil {
		return nil, err
	}
	var result []RestWatchStandingsResponseItem
	if err := json.Unmarshal(data, &result); err != nil {
		return nil, err
	}
	return result, nil
}

func (c *Client) RestWatchStandingsHistory() (*map[string][]RestWatchStandingsHistoryResponseItemItem, error) {
	data, err := c.doRequest("GET", "/rest/watch/standings/history", nil)
	if err != nil {
		return nil, err
	}
	var result map[string][]RestWatchStandingsHistoryResponseItemItem
	if err := json.Unmarshal(data, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) RestWatchTrackmap() ([]RestWatchTrackmapResponseItem, error) {
	data, err := c.doRequest("GET", "/rest/watch/trackmap", nil)
	if err != nil {
		return nil, err
	}
	var result []RestWatchTrackmapResponseItem
	if err := json.Unmarshal(data, &result); err != nil {
		return nil, err
	}
	return result, nil
}

func (c *Client) PostWebdata() (json.RawMessage, error) {
	data, err := c.doRequest("POST", "/webdata/.*", nil)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func (c *Client) Webdata() (json.RawMessage, error) {
	data, err := c.doRequest("GET", "/webdata/.*", nil)
	if err != nil {
		return nil, err
	}
	return data, nil
}
